[pytest]
markers =
    osnovnye: основные операции с задачами
    otobrazhenie: тесты отображения задач
    exceptions: тесты, проверяющие исключения
    data: тест с параметризацией
# Отключаем Unicode в выводе (для красивого вывода)
disable_test_id_escaping_and_forfeit_all_rights_to_community_support = True
